version: '3'

services: 

    server:
        build: 
            context: ./server
        volumes: 
            - ./server:/app
        ports: 
            - 3099:3099
        environment: 
            - PORT:3099

    web-client:
        build: 
            context: ./web-client
        volumes: 
            - ./web-client/htdocs:/usr/share/nginx/html
            - ./web-client/nginx/nginx.conf:/etc/nginx/conf.d/default.template:ro
        ports: 
            - 3002:80
        env_file: ./web-client/.env

    react-client:
        build: 
            context: ./react-client
        volumes: 
            - ./react-client/app:/app
        ports: 
            - 3003:3000
        env_file: ./react-client/app/.env.local